apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate-trader
  organization: tetrate-workshop
  workspace: portfolio-workspace
  name: portfolio-gateway
spec:
  displayName: portfolio-gateway
  description: portfolio-gateway
  namespaceSelector:
    names:
      - "*/portfolio"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: portfolio-gw
  group: portfolio-gateway
  workspace: portfolio-workspace
  tenant: tetrate-trader
  organization: tetrate-workshop
spec:
  workloadSelector:
    namespace: portfolio
    labels:
      app: tsb-gateway-portfolio
  http:
    - name: portfolio-gw
      port: 443
      hostname: "portfolio.trader.cloud.zwickey.net"
      tls:
        mode: SIMPLE
        secretName: portfolio-cert
      routing:
        rules:
          - route:
              host: "portfolio/portfolio-service.portfolio.svc.cluster.local"
              port: 8080